In [1]:
import numpy as np

In [6]:
#1
n50_100=np.arange(50,101)
n50_100

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
#2
t1=np.repeat(1,10)
t0=np.repeat(0,10)
t6=np.repeat(6,10)
print(t1,t0,t6)

[1 1 1 1 1 1 1 1 1 1] [0 0 0 0 0 0 0 0 0 0] [6 6 6 6 6 6 6 6 6 6]


In [14]:
#3
n20_24=np.arange(20,24)
n24_28=np.arange(24,28)
n28_32=np.arange(28,32)
n20_32=np.vstack([n20_24,n24_28,n28_32])
n20_32

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [15]:
#4
d1=np.eye(3)
d1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#5
d15=np.diag(np.arange(1,6))
d15

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [25]:
#6
b6=np.array([np.arange(5,18,3),np.arange(1,10,2),np.arange(7,28,5),np.arange(4,57,13)])
print(b6)
print(b6.sum())
print("Багана",b6.sum(axis=0))
print('Мөр',b6.sum(axis=1))

[[ 5  8 11 14 17]
 [ 1  3  5  7  9]
 [ 7 12 17 22 27]
 [ 4 17 30 43 56]]
315
Багана [ 17  40  63  86 109]
Мөр [ 55  25  85 150]


In [32]:
#7 Хөл бөмбөг
#Messi, Ronaldo, Neymar, Di Maria, Modric, Harry Kane, De Bruyne, Benzema, Lewandowski, Courtois
#Players
PDic={"ThibautCourtois":0,"LionelMessi":1,"CristianoRonaldo":2,"NeymarJr":3,"AngelDiMaria":4,"LukaModric":5,"HarryKane":6,"KevinDeBruyne":7,"KarimBenzema":8,"RobertLewandowski":9}
#Seasons
SDic={"2013-2014":0,"2014-2015":1,"2015-2016":2,"2016-2017":3,"2017-2018":4,"2018-2019":5,"2019-2020":6,"2020-2021":7,"2021-2022":8,"2022-2023":9}
#Salaries Source:Capology

Sal_T_Courtois=[1207943,6310390,6310390,6310390,6310390,13791552,13791552,13791552,15755772,15755772]
Sal_L_Messi=[21574904,31122902,29904455,40208730,41616246,74325228,74577321,73577321,66846489,66846489]
Sal_C_Ronaldo=[34526148,30513678,29326744,35366456,36605910,60302591,60302591,60302591,32498507,32498507]
Sal_Neymar=[13171825,11585744,17772511,30062013,45481662,45481662,45481662,59199687,59199687,59199687]
Sal_A_Maria=[4000000,15775974,9001798,10692817,13833568,13970118,13865079,13865079,13865079,8077459]
Sal_L_Modric=[8455598,8035444,7730832,14894456,15409145,19579173,22982419,22982419,22982419,22982419]
Sal_H_Kane=[3155519,3155519,3155519,6310390,6310390,12620780,12620780,12620780,12620780,12620780]
Sal_K_Bruyne=[4936809,4338089,9465585,9465585,11043182,22086364,22086364,25241559,25241559,25241559]
Sal_K_Benzema=[10419817,14348256,13791552,16627591,17215807,17373365,19032973,19043476,25209235,25209235]
Sal_R_Lewandowski=[4936809,7804359,7499747,15031006,16596080,16753638,24158850,24158850,24158850,21879515]
Salary=np.array([Sal_T_Courtois,Sal_L_Messi,Sal_C_Ronaldo,Sal_Neymar,Sal_A_Maria,Sal_L_Modric,Sal_H_Kane,Sal_K_Bruyne,Sal_K_Benzema,Sal_R_Lewandowski])

#Games Domestic League

G_T_Courtois=[37,32,23,36,35,27,34,38,36,31]
G_L_Messi=[31,38,33,34,36,34,33,35,26,32]
G_C_Ronaldo=[30,35,36,29,27,31,33,33,31,26]
G_Neymar=[26,33,34,30,20,17,15,18,22,20]
G_A_Maria=[34,27,29,29,30,30,26,27,26,26]
G_L_Modric=[34,16,32,25,26,34,31,35,28,33]
G_H_Kane=[10,34,38,30,37,28,29,35,37,38]
G_K_Bruyne=[19,34,27,36,37,19,35,25,30,32]
G_K_Benzema=[35,29,27,29,32,36,37,34,32,24]
G_R_Lewandowski=[33,31,32,33,30,33,31,29,34,34]
GamesDL=np.array([G_T_Courtois,G_L_Messi,G_C_Ronaldo,G_Neymar,G_A_Maria,G_L_Modric,G_H_Kane,G_K_Bruyne,G_K_Benzema,G_R_Lewandowski])

#Goals Domestic League
Gl_T_Courtois=[24,30,29,28,34,36,20,28,29,29]
Gl_L_Messi=[28,43,26,37,34,36,25,30,6,16]
Gl_C_Ronaldo=[31,48,35,25,26,21,31,29,18,15]
Gl_Neymar=[9,22,24,13,19,15,13,9,13,13]
Gl_A_Maria=[4,3,10,6,11,12,8,4,5,4]
Gl_L_Modric=[1,1,2,1,1,3,3,5,2,4]
Gl_H_Kane=[3,21,25,29,30,17,18,23,17,30]
Gl_K_Bruyne=[3,10,7,6,8,2,13,6,15,7]
Gl_K_Benzema=[17,15,24,11,5,21,21,23,27,19]
Gl_R_Lewandowski=[20,17,30,30,29,22,34,41,35,23]
GoalsDL=np.array([Gl_T_Courtois,Gl_L_Messi,Gl_C_Ronaldo,Gl_Neymar,Gl_A_Maria,Gl_L_Modric,Gl_H_Kane,Gl_K_Bruyne,Gl_K_Benzema,Gl_R_Lewandowski])
print(Salary,GamesDL,GoalsDL)

[[ 1207943  6310390  6310390  6310390  6310390 13791552 13791552 13791552
  15755772 15755772]
 [21574904 31122902 29904455 40208730 41616246 74325228 74577321 73577321
  66846489 66846489]
 [34526148 30513678 29326744 35366456 36605910 60302591 60302591 60302591
  32498507 32498507]
 [13171825 11585744 17772511 30062013 45481662 45481662 45481662 59199687
  59199687 59199687]
 [ 4000000 15775974  9001798 10692817 13833568 13970118 13865079 13865079
  13865079  8077459]
 [ 8455598  8035444  7730832 14894456 15409145 19579173 22982419 22982419
  22982419 22982419]
 [ 3155519  3155519  3155519  6310390  6310390 12620780 12620780 12620780
  12620780 12620780]
 [ 4936809  4338089  9465585  9465585 11043182 22086364 22086364 25241559
  25241559 25241559]
 [10419817 14348256 13791552 16627591 17215807 17373365 19032973 19043476
  25209235 25209235]
 [ 4936809  7804359  7499747 15031006 16596080 16753638 24158850 24158850
  24158850 21879515]] [[37 32 23 36 35 27 34 38 36 31]
 [31 38 33 34 36

In [34]:
print('Улирлаар')
print('Salary',Salary.sum(axis=0))
print('Games:Domestic League',GamesDL.sum(axis=0))
print('Goals:Domestic League',GoalsDL.sum(axis=0))
print('Тоглогчоор')
print('Salary',Salary.sum(axis=1))
print('Games:Domestic League',GamesDL.sum(axis=1))
print('Goals:Domestic League',GoalsDL.sum(axis=1))

Улирлаар
Salary [106385372 132990355 133959133 184969434 210422380 296284471 308899591
 324783314 298378377 290311422]
Games:Domestic League [289 309 311 311 310 289 304 309 302 296]
Goals:Domestic League [140 210 212 186 197 185 186 198 167 160]
Тоглогчоор
Salary [ 99335703 520600085 412243723 386636140 116946971 166034324  85191237
 159146655 178271307 162977704]
Games:Domestic League [329 332 311 235 284 294 316 294 315 320]
Goals:Domestic League [287 281 279 150  67  23 213  77 183 281]


In [38]:
GoalsDL[PDic["LionelMessi"],SDic['2014-2015']]

43